// <auto-generated by tools/generate_preview_map_cs.py — do not hand-edit>
#nullable enable
using System;
using System.Collections.Generic;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.Models;

namespace YgoDuelist.YgoDuelistCode.Services
{
/// <summary>Registry of preview card types from quoted names in localization (merged on cards via PreviewReferencedCardTypes).</summary>
public static class YgoPreviewReferencedCardTypes
{
    private static readonly Dictionary<Type, Type[]> Map = new()
    {
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.A_Cat_of_Ill_Omen)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Field.Necrovalley) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Normal.A_Deal_with_Dark_Ruler)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Berserk_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Field.A_Legendary_Ocean)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Field.Umi) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Alligator_S_Sword_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Alligator_S_Sword), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Baby_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Amphibious_Bugroth)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Ground_Attacker_Bugroth), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Sentinel_of_the_Seas) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Amphibious_Bugroth_MK_3)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Field.Umi) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Normal.Ancient_Chant)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.The_Winged_Dragon_of_Ra) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Ancient_Lamp)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.La_Jinn_the_Mystical_Genie_of_the_Lamp) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Aqua_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Amazon_of_the_Seas), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Fairy_Dragon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Zone_Eater) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Barox)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Frenzied_Panda), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Ryu_Kishin) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Beastly_Mirror_Ritual)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Fiend_S_Mirror) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Berfomet)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Gazelle_the_King_of_Mythical_Beasts) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Berserk_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Normal.A_Deal_with_Dark_Ruler) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Bickuribox)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Crass_Clown), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Dream_Clown) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Birdface)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Harpie_Lady) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Black_Illusion_Ritual)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Relinquished) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Black_Luster_Ritual)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Black_Luster_Soldier) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Black_Luster_Soldier)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Black_Luster_Ritual) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Black_Magic_Ritual)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Magician_of_Black_Chaos) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Black_Skull_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Red_Eyes_Black_Dragon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Summoned_Skull) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Blue_Eyes_Ultimate_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Blue_Eyes_White_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Bracchio_Raidus)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Crawling_Dragon_2), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Two_Headed_King_Rex) },
        //[typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Cannonball_Spear_Shellfish)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Field.Umi) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Chakra)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Resurrection_of_Chakra) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Charubin_the_Fire_Knight)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Hinotama_Soul), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Monster_Egg) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Chimera_the_Flying_Mythical_Beast)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Berfomet), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Gazelle_the_King_of_Mythical_Beasts) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Cobra_Jar)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Token.Poisonous_Snake_Token) },
        //[typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Cocoon_of_Evolution)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Petit_Moth) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Commencement_Dance)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Performance_of_Sword) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Contract_with_the_Dark_Master)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Dark_Master_Zorc) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Crab_Turtle)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Turtle_Oath) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Crimson_Sunbird)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Faith_Bird), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Skull_Red_Bird) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Curse_of_the_Masked_Beast)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.The_Masked_Beast) },
        //[typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Cyber_Harpie_Lady)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Harpie_Lady) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Cyber_Saurus)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Blast_Juggler), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Two_Headed_King_Rex) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Dark_Balter_the_Terrible)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Frontier_Wiseman), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Possessed_Dark_Soul) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Dark_Blade_the_Dragon_Knight)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Dark_Blade), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Pitch_Dark_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Dark_Flare_Knight)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Dark_Magician), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Flame_Swordsman), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Mirage_Knight) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Normal.Dark_Magic_Attack)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Dark_Magician) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Dark_Master_Zorc)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Contract_with_the_Dark_Master) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Dark_Paladin)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Buster_Blader), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Dark_Magician) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Darkfire_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Firegrass), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Petit_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Deepsea_Shark)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Bottom_Dweller), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Tongyo) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Dokurorider)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Revival_of_Dokurorider) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Dragon_Master_Knight)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Black_Luster_Soldier), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Blue_Eyes_Ultimate_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Dragoness_the_Wicked_Knight)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Armaill), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.One_Eyed_Shield_Dragon) },
        //[typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Drill_Bug)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Parasite_Paracide) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Empress_Judge)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Hibikime), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Queen_s_Double) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Exodia_the_Forbidden_One)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Left_Arm_of_the_Forbidden_One) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Fiend_S_Mirror)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Beastly_Mirror_Ritual) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Flame_Ghost)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Dissolverock), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Skull_Servant) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Flame_Swordsman)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Flame_Manipulator), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Masaki_the_Legendary_Swordsman) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Flower_Wolf)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Darkworld_Thorns), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Silver_Fang) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Fortress_Whale)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Fortress_Whale_S_Oath) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Fortress_Whale_S_Oath)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Fortress_Whale) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Normal.Fusion_Sage)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Normal.Polymerization) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Fusionist)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Mystical_Sheep_2), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Petit_Angel) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Gaia_the_Dragon_Champion)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Curse_of_Dragon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Gaia_The_Fierce_Knight) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Garma_Sword)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Garma_Sword_Oath) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Garma_Sword_Oath)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Garma_Sword) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Gate_Guardian)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Kazejin), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Sanga_of_the_Thunder), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Suijin) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Gatling_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Barrel_Dragon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Blowback_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Giltia_the_D_Knight)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Guardian_of_the_Labyrinth), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Protector_of_the_Throne) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Gravekeeper_s_Assailant)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Field.Necrovalley) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Great_Dezard)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Fushioh_Richie) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Great_Mammoth_of_Goldfine)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Dragon_Zombie), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.The_Snake_Hair) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Guardian_Slime)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Normal.Ancient_Chant) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Hamburger_Recipe)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Hungry_Burger) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Harpie_S_Pet_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Harpie_Lady) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Humanoid_Worm_Drake)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Humanoid_Slime), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Worm_Drake) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Hungry_Burger)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Hamburger_Recipe) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Incandescent_Ordeal)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Legendary_Flame_Lord) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Insect_Queen)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Token.Insect_Monster_Token) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Continuos.Jam_Breeding_Machine)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Token.Slime_Token) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Javelin_Beetle)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Javelin_Beetle_Pact) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Javelin_Beetle_Pact)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Javelin_Beetle) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Kaiser_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Fairy_Dragon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Winged_Dragon_Guardian_of_the_Fortress_1) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Kaminari_Attack)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Mega_Thunderball), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Ocubeam) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Kamionwizard)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Curtain_of_the_Dark_Ones), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Mystical_Elf) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Karbonala_Warrior)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.M_Warrior_1), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.M_Warrior_2) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.King_Dragun)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Divine_Dragon_Ragnarok), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Lord_of_D) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.King_of_the_Swamp)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Normal.Polymerization) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Kiryu)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Dark_Blade) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Kwagar_Hercules)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Hercules_Beetle), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Kuwagata) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Labyrinth_Tank)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Cannon_Soldier), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Giga_Tech_Wolf) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Legendary_Flame_Lord)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Incandescent_Ordeal) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Lekunga)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Token.Lekunga_Token) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Magician_of_Black_Chaos)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Black_Magic_Ritual) },
        //[typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Maiden_of_the_Aqua)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Field.Umi) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Man_Eating_Black_Shark)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Amazon_of_the_Seas), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Gruesome_Goo), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Sea_Kamen) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Marine_Beast)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Behegon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Water_Magician) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Master_of_Oz)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Big_Koala), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Des_Kangaroo) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Mavelus)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Tyhone), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Wings_of_Wicked_Flame) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Mermaid_Knight)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Field.Umi) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Metal_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Lesser_Dragon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Steel_Ogre_Grotto_1) },
        //[typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Metalzoa)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Zoa) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Meteor_Black_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Meteor_Dragon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Red_Eyes_Black_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Mokey_Mokey_King)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Mokey_Mokey) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Monster_Eye)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Normal.Polymerization) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Normal.Multiply)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Kuriboh) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Musician_King)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Lady_of_Faith), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Witch_of_the_Black_Forest) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Mystical_Sand)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Ancient_Elf), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Giant_Soldier_of_Stone) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Novox_S_Prayer)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Skull_Guardian) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Ocean_Dragon_Lord_Neo_Daedalus)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Levia_Dragon_Daedalus) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Ojama_King)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Ojama_Black), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Ojama_Green), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Ojama_Yellow) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Orca_Mega_Fortress_of_Darkness)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Torpedo_Fish) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Paladin_of_White_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Blue_Eyes_White_Dragon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.White_Dragon_Ritual) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Performance_of_Sword)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Commencement_Dance) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Trap.Done.Normal.Physical_Double)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Token.Mirage_Token) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Pragtical)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Flame_Viper), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Trakodon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Punished_Eagle)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Blue_Winged_Crown), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Niwatori) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Rabid_Horseman)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Battle_Ox), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Mystic_Horseman) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Rare_Fish)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Enchanting_Mermaid), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Fusionist) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Reactor_Slime)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Trap.Done.Linked.Metal_Reflect_Slime), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Token.Slime_Token) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Reaper_on_the_Nightmare)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Nightmare_Horse), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Spirit_Reaper) },
        //[typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Red_Eyes_Black_Metal_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Red_Eyes_Black_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Relinquished)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Black_Illusion_Ritual) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Resurrection_of_Chakra)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Chakra) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Revival_of_Dokurorider)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Dokurorider) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Roaring_Ocean_Snake)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Hyosube), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Mystic_Lamp) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Rose_Spectre_of_Dunn)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Feral_Imp), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Snakeyashi) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Ryu_Senshi)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Spirit_Ryu), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Warrior_Dai_Grepher) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Sanwitch)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Sangan), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Witch_of_the_Black_Forest) },
        //[typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Second_Goblin)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Giant_Orc) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Shinato_King_of_a_Higher_Plane)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Shinato_S_Ark) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Shinato_S_Ark)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Shinato_King_of_a_Higher_Plane) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Skelgon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Blackland_Fire_Dragon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.The_Snake_Hair) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Skull_Guardian)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Novox_S_Prayer) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Skull_Knight)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Ancient_Brain), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Tainted_Wisdom) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Skullbird)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Takuhee), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Temple_of_Skulls) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Soul_Hunter)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Invader_from_Another_Dimension), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Lord_of_the_Lamp) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Command.Special_Summon_Egyptian_God_Slime)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Egyptian_God_Slime) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Command.Special_Summon_Wall_Shadow)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Wall_Shadow) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Command.Special_Summon_Dark_Sage)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Dark_Sage) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.St_Joan)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Darklord_Marie), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.The_Forgiving_Maiden) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Trap.Done.Normal.Statue_of_the_Wicked)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Token.Wicked_Token) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Super_War_Lion)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.War_Lion_Ritual) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.The_Agent_of_Creation_Venus)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Mystical_Shine_Ball) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.The_Last_Warrior_from_Another_Planet)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Maryokutai), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Zombyra_the_Dark) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.The_Masked_Beast)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Curse_of_the_Masked_Beast) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Thousand_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Baby_Dragon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Time_Wizard) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Thousand_Eyes_Restrict)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Relinquished), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Thousand_Eyes_Idol) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Turtle_Oath)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Crab_Turtle) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Twin_Headed_Thunder_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Effect.Thunder_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Vermillion_Sparrow)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Fireyarou), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Rhaimundos_of_the_Red_Sword) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Vw_Tiger_Catapult)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.V_Tiger_Jet), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.W_Wing_Catapult) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Vwxyz_Dragon_Catapult_Cannon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Vw_Tiger_Catapult), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Xyz_Dragon_Cannon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.War_Lion_Ritual)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Super_War_Lion) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Warrior_of_Tradition)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Beautiful_Headhuntress), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Sonic_Maid) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.White_Dragon_Ritual)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Paladin_of_White_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Xy_Dragon_Cannon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.X_Head_Cannon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Y_Dragon_Head) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Xyz_Dragon_Cannon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.X_Head_Cannon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Y_Dragon_Head), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Z_Metal_Tank) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Xz_Tank_Cannon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.X_Head_Cannon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Z_Metal_Tank) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Yz_Tank_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Y_Dragon_Head), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Z_Metal_Tank) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Zera_Ritual)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Zera_the_Mant) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Ritual.Zera_the_Mant)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Done.Ritual.Zera_Ritual) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Fusion.Zombie_Warrior)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Battle_Warrior), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Done.Normal.Skull_Servant) },
    };

    /// <summary>Preview targets derived from quoted card names in <c>cards.json</c>.</summary>
    public static Type[] FromLocalizationQuotes(Type hostCardType)
    {
        if (!Map.TryGetValue(hostCardType, out Type[]? arr) || arr == null || arr.Length == 0)
            return Array.Empty<Type>();
        int keep = 0;
        foreach (Type? t in arr)
        {
            if (t != null && t != hostCardType)
                keep++;
        }
        if (keep == 0)
            return Array.Empty<Type>();
        if (keep == arr.Length)
            return arr;
        var filtered = new Type[keep];
        int i = 0;
        foreach (Type? t in arr)
        {
            if (t != null && t != hostCardType)
                filtered[i++] = t;
        }
        return filtered;
    }

    /// <summary>Merges localization-derived previews with explicit extras (deduped; never includes <paramref name="hostCardType"/>).</summary>
    public static Type[] Merged(Type hostCardType, params Type[]? extras)
    {
        Type[] fromQuotes = FromLocalizationQuotes(hostCardType);
        if (extras == null || extras.Length == 0)
            return fromQuotes;
        var seen = new HashSet<Type>();
        var list = new List<Type>();
        foreach (Type? t in fromQuotes)
        {
            if (t != null && t != hostCardType && seen.Add(t))
                list.Add(t);
        }
        foreach (Type? t in extras)
        {
            if (t != null && t != hostCardType && seen.Add(t))
                list.Add(t);
        }
        return list.ToArray();
    }

    public static IEnumerable<IHoverTip> EnumerateHoverTips(Type hostCardType)
    {
        foreach (Type t in FromLocalizationQuotes(hostCardType))
        {
            if (t == null)
                continue;
            CardModel template = YgoPackCardCatalog.CardFromType(t);
            yield return HoverTipFactory.FromCard(template);
        }
    }
}
}
