// <auto-generated by tools/generate_preview_map_cs.py — do not hand-edit>
using System;
using System.Collections.Generic;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.Models;

namespace YgoDuelist.YgoDuelistCode.Services
{
/// <summary>Registry of preview card types from quoted names in localization (merged on cards via PreviewReferencedCardTypes).</summary>
public static class YgoPreviewReferencedCardTypes
{
    private static readonly Dictionary<Type, Type[]> Map = new()
    {
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.A_Cat_of_Ill_Omen)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Field.Necrovalley) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Normal.A_Deal_with_Dark_Ruler)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Berserk_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Field.A_Legendary_Ocean)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Field.Umi) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Alligator_S_Sword_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Alligator_S_Sword), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Baby_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Amphibious_Bugroth)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Ground_Attacker_Bugroth), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Sentinel_of_the_Seas) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Amphibious_Bugroth_MK_3)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Field.Umi) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Normal.Ancient_Chant)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.The_Winged_Dragon_of_Ra) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Ancient_Lamp)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.La_Jinn_the_Mystical_Genie_of_the_Lamp) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Aqua_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Amazon_of_the_Seas), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Fairy_Dragon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Zone_Eater) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Barox)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Frenzied_Panda), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Ryu_Kishin) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Beastly_Mirror_Ritual)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Fiend_S_Mirror) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Berfomet)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Gazelle_the_King_of_Mythical_Beasts) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Berserk_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Normal.A_Deal_with_Dark_Ruler) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Bickuribox)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Crass_Clown), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Dream_Clown) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Birdface)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Harpie_Lady) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Black_Illusion_Ritual)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Relinquished) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Black_Luster_Ritual)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Black_Luster_Soldier) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Black_Luster_Soldier)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Black_Luster_Ritual) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Black_Magic_Ritual)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Magician_of_Black_Chaos) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Black_Skull_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Red_Eyes_Black_Dragon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Summoned_Skull) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Blue_Eyes_Ultimate_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Blue_Eyes_White_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Bracchio_Raidus)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Crawling_Dragon_2), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Two_Headed_King_Rex) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Cannonball_Spear_Shellfish)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Field.Umi) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Chakra)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Resurrection_of_Chakra) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Charubin_the_Fire_Knight)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Hinotama_Soul), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Monster_Egg) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Chimera_the_Flying_Mythical_Beast)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Berfomet), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Gazelle_the_King_of_Mythical_Beasts) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Cobra_Jar)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Token.Poisonous_Snake_Token) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Cocoon_of_Evolution)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Petit_Moth) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Commencement_Dance)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Performance_of_Sword) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Contract_with_the_Dark_Master)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Dark_Master_Zorc) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Crab_Turtle)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Turtle_Oath) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Crimson_Sunbird)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Faith_Bird), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Skull_Red_Bird) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Curse_of_the_Masked_Beast)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.The_Masked_Beast) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Cyber_Harpie_Lady)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Harpie_Lady) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Cyber_Saurus)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Blast_Juggler), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Two_Headed_King_Rex) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Dark_Balter_the_Terrible)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Frontier_Wiseman), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Possessed_Dark_Soul) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Dark_Blade_the_Dragon_Knight)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Dark_Blade), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Pitch_Dark_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Dark_Flare_Knight)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Dark_Magician), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Flame_Swordsman), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Mirage_Knight) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Normal.Dark_Magic_Attack)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Dark_Magician) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Dark_Magician_Girl)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Dark_Magician), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Magician_of_Black_Chaos) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Dark_Master_Zorc)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Contract_with_the_Dark_Master) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Dark_Paladin)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Buster_Blader), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Dark_Magician) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Darkfire_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Firegrass), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Petit_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Deepsea_Shark)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Bottom_Dweller), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Tongyo) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Dokurorider)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Revival_of_Dokurorider) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Dragon_Master_Knight)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Black_Luster_Soldier), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Blue_Eyes_Ultimate_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Dragoness_the_Wicked_Knight)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Armaill), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.One_Eyed_Shield_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Drill_Bug)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Parasite_Paracide) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Empress_Judge)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Hibikime), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Queen_s_Double) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Exodia_the_Forbidden_One)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Left_Arm_of_the_Forbidden_One) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Fiend_S_Mirror)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Beastly_Mirror_Ritual) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Flame_Ghost)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Dissolverock), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Skull_Servant) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Flame_Swordsman)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Flame_Manipulator), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Masaki_the_Legendary_Swordsman) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Flower_Wolf)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Darkworld_Thorns), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Silver_Fang) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Fortress_Whale)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Fortress_Whale_S_Oath) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Fortress_Whale_S_Oath)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Fortress_Whale) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Normal.Fusion_Sage)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Normal.Polymerization) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Fusionist)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Mystical_Sheep_2), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Petit_Angel) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Gaia_the_Dragon_Champion)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Curse_of_Dragon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Gaia_The_Fierce_Knight) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Garma_Sword)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Garma_Sword_Oath) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Garma_Sword_Oath)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Garma_Sword) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Gate_Guardian)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Kazejin), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Sanga_of_the_Thunder), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Suijin) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Gatling_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Barrel_Dragon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Blowback_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Giltia_the_D_Knight)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Guardian_of_the_Labyrinth), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Protector_of_the_Throne) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Gravekeeper_s_Assailant)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Field.Necrovalley) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Great_Dezard)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Fushioh_Richie) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Great_Mammoth_of_Goldfine)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Dragon_Zombie), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.The_Snake_Hair) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Guardian_Baou)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Equip.Wicked_Breaking_Flamberge_Baou) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Guardian_Ceal)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Equip.Shooting_Star_Bow_Ceal) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Guardian_Elma)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Equip.Butterfly_Dagger_Elma) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Guardian_Kay_est)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Equip.Rod_of_Silence_Kay_est) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Guardian_Slime)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Normal.Ancient_Chant) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Guardian_Tryce)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Equip.Twin_Swords_of_Flashing_Light_Tryce) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Hamburger_Recipe)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Hungry_Burger) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Harpie_Lady_Sisters)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Normal.Elegant_Egotist) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Harpie_S_Pet_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Harpie_Lady) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Humanoid_Worm_Drake)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Humanoid_Slime), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Worm_Drake) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Hungry_Burger)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Hamburger_Recipe) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Incandescent_Ordeal)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Legendary_Flame_Lord) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Insect_Queen)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Token.Insect_Monster_Token) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Continuos.Jam_Breeding_Machine)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Token.Slime_Token) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Javelin_Beetle)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Javelin_Beetle_Pact) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Javelin_Beetle_Pact)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Javelin_Beetle) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Kaiser_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Fairy_Dragon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Winged_Dragon_Guardian_of_the_Fortress_1) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Kaminari_Attack)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Mega_Thunderball), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Ocubeam) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Kamionwizard)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Curtain_of_the_Dark_Ones), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Mystical_Elf) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Karbonala_Warrior)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.M_Warrior_1), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.M_Warrior_2) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.King_Dragun)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Divine_Dragon_Ragnarok), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Lord_of_D) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Kiryu)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Dark_Blade) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Kwagar_Hercules)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Hercules_Beetle), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Kuwagata) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Labyrinth_Tank)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Cannon_Soldier), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Giga_Tech_Wolf) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Legendary_Flame_Lord)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Incandescent_Ordeal) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Lekunga)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Token.Lekunga_Token) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Levia_Dragon_Daedalus)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Field.Umi) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Magician_of_Black_Chaos)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Black_Magic_Ritual) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Maiden_of_the_Aqua)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Field.Umi) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Man_Eating_Black_Shark)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Amazon_of_the_Seas), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Gruesome_Goo), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Sea_Kamen) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Marine_Beast)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Behegon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Water_Magician) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Master_of_Oz)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Big_Koala), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Des_Kangaroo) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Mavelus)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Tyhone), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Wings_of_Wicked_Flame) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Mermaid_Knight)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Field.Umi) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Metal_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Lesser_Dragon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Steel_Ogre_Grotto_1) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Metalzoa)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Trap.Todo.Normal.Metalmorph), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Zoa) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Meteor_Black_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Meteor_Dragon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Red_Eyes_Black_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Mokey_Mokey_King)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Mokey_Mokey) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Monster_Eye)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Normal.Polymerization) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Normal.Multiply)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Kuriboh) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Musician_King)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Lady_of_Faith), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Witch_of_the_Black_Forest) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Mystical_Sand)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Ancient_Elf), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Giant_Soldier_of_Stone) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Novox_S_Prayer)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Skull_Guardian) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Ojama_King)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Ojama_Black), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Ojama_Green), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Ojama_Yellow) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Orca_Mega_Fortress_of_Darkness)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Torpedo_Fish) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Paladin_of_White_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Blue_Eyes_White_Dragon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.White_Dragon_Ritual) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Pandemonium_Watchbear)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Field.Pandemonium) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Performance_of_Sword)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Commencement_Dance) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Trap.Todo.Normal.Physical_Double)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Token.Mirage_Token) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Pragtical)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Flame_Viper), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Trakodon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Pumpking_the_King_of_Ghosts)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Castle_of_Dark_Illusions) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Punished_Eagle)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Blue_Winged_Crown), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Niwatori) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Rabid_Horseman)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Battle_Ox), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Mystic_Horseman) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Rare_Fish)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Enchanting_Mermaid), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Fusionist) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Reactor_Slime)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Trap.Todo.Continuos.Metal_Reflect_Slime), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Token.Slime_Token) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Reaper_on_the_Nightmare)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Nightmare_Horse), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Spirit_Reaper) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Red_Eyes_Black_Metal_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Trap.Todo.Normal.Metalmorph), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Red_Eyes_Black_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Relinquished)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Black_Illusion_Ritual) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Resurrection_of_Chakra)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Chakra) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Revival_of_Dokurorider)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Dokurorider) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Roaring_Ocean_Snake)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Hyosube), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Mystic_Lamp) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Rose_Spectre_of_Dunn)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Feral_Imp), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Snakeyashi) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Ryu_Senshi)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Spirit_Ryu), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Warrior_Dai_Grepher) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Sanwitch)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Sangan), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Witch_of_the_Black_Forest) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Second_Goblin)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Giant_Orc) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Shinato_King_of_a_Higher_Plane)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Shinato_S_Ark) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Shinato_S_Ark)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Shinato_King_of_a_Higher_Plane) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Skelgon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Blackland_Fire_Dragon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.The_Snake_Hair) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Skull_Guardian)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Novox_S_Prayer) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Skull_Knight)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Ancient_Brain), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Tainted_Wisdom) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Skullbird)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Takuhee), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Temple_of_Skulls) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Soul_Hunter)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Invader_from_Another_Dimension), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Lord_of_the_Lamp) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Command.Special_Summon_Egyptian_God_Slime)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Egyptian_God_Slime) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.St_Joan)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Darklord_Marie), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.The_Forgiving_Maiden) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Trap.Todo.Normal.Statue_of_the_Wicked)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Token.Wicked_Token) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Super_War_Lion)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.War_Lion_Ritual) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.The_Agent_of_Creation_Venus)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Mystical_Shine_Ball) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.The_Last_Warrior_from_Another_Planet)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Maryokutai), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Zombyra_the_Dark) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.The_Masked_Beast)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Curse_of_the_Masked_Beast) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Thousand_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Baby_Dragon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Time_Wizard) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Thousand_Eyes_Restrict)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Relinquished), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Thousand_Eyes_Idol) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Turtle_Oath)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Crab_Turtle) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Twin_Headed_Thunder_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Thunder_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Vermillion_Sparrow)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Fireyarou), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Rhaimundos_of_the_Red_Sword) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Vw_Tiger_Catapult)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Normal.Polymerization), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.V_Tiger_Jet), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.W_Wing_Catapult) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Vwxyz_Dragon_Catapult_Cannon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Normal.Polymerization), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Xyz_Dragon_Cannon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.W_Wing_Catapult)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.V_Tiger_Jet) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Wall_Shadow)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Equip.Magical_Labyrinth) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.War_Lion_Ritual)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Super_War_Lion) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Warrior_of_Tradition)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Beautiful_Headhuntress), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Sonic_Maid) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.White_Dragon_Ritual)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Paladin_of_White_Dragon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Trap.Todo.Normal.White_Hole)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Normal.Dark_Hole) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Xy_Dragon_Cannon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Normal.Polymerization), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.X_Head_Cannon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Y_Dragon_Head) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Xyz_Dragon_Cannon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Normal.Polymerization), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.X_Head_Cannon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Y_Dragon_Head), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Z_Metal_Tank) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Xz_Tank_Cannon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Normal.Polymerization), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.X_Head_Cannon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Z_Metal_Tank) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Y_Dragon_Head)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.X_Head_Cannon) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Yz_Tank_Dragon)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Normal.Polymerization), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Y_Dragon_Head), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Z_Metal_Tank) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Z_Metal_Tank)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.X_Head_Cannon), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Effect.Y_Dragon_Head) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Zera_Ritual)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Zera_the_Mant) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Ritual.Zera_the_Mant)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Spell.Todo.Ritual.Zera_Ritual) },
        [typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Fusion.Zombie_Warrior)] = new[] { typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Battle_Warrior), typeof(global::YgoDuelist.YgoDuelistCode.Cards.Monster.Todo.Normal.Skull_Servant) },
    };

    /// <summary>Preview targets derived from quoted card names in <c>cards.json</c>.</summary>
    public static Type[] FromLocalizationQuotes(Type hostCardType)
    {
        if (!Map.TryGetValue(hostCardType, out Type[]? arr) || arr == null || arr.Length == 0)
            return Array.Empty<Type>();
        int keep = 0;
        foreach (Type? t in arr)
        {
            if (t != null && t != hostCardType)
                keep++;
        }
        if (keep == 0)
            return Array.Empty<Type>();
        if (keep == arr.Length)
            return arr;
        var filtered = new Type[keep];
        int i = 0;
        foreach (Type? t in arr)
        {
            if (t != null && t != hostCardType)
                filtered[i++] = t;
        }
        return filtered;
    }

    /// <summary>Merges localization-derived previews with explicit extras (deduped; never includes <paramref name="hostCardType"/>).</summary>
    public static Type[] Merged(Type hostCardType, params Type[]? extras)
    {
        Type[] fromQuotes = FromLocalizationQuotes(hostCardType);
        if (extras == null || extras.Length == 0)
            return fromQuotes;
        var seen = new HashSet<Type>();
        var list = new List<Type>();
        foreach (Type? t in fromQuotes)
        {
            if (t != null && t != hostCardType && seen.Add(t))
                list.Add(t);
        }
        foreach (Type? t in extras)
        {
            if (t != null && t != hostCardType && seen.Add(t))
                list.Add(t);
        }
        return list.ToArray();
    }

    public static IEnumerable<IHoverTip> EnumerateHoverTips(Type hostCardType)
    {
        foreach (Type t in FromLocalizationQuotes(hostCardType))
        {
            if (t == null)
                continue;
            CardModel template = YgoPackCardCatalog.CardFromType(t);
            yield return HoverTipFactory.FromCard(template);
        }
    }
}
}
