"""Generate YgoReferencedCardPreviewMap.cs from cards.json + card classes."""
import json
import os
import re
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_PATH = os.path.join(ROOT, "YgoDuelist", "localization", "eng", "cards.json")
CARDS_CS = os.path.join(ROOT, "YgoDuelistCode", "Cards")
OUT_PATH = os.path.join(ROOT, "YgoDuelistCode", "Services", "YgoReferencedCardPreviewMap.cs")

# Quoted text in descriptions -> C# class name, or None = archetype / not a specific card (no preview).
QUOTE_TO_CLASS: dict[str, str | None] = {
    "Guardian": None,
    "Phantom Beast": None,
    "Toon": None,
    "Ninja": None,
    "Gravekeeper's": None,
    "Archfiend": None,
    "Temple of the Kings": None,
    "Spirit of Pharaoh": None,
    "Des Dendle": None,
    "Slime Tokens": "Slime_Token",
    "Metal Reflect Slime": "Metal_Reflect_Slime",
    "Wicked Token(s)": "Wicked_Token",
    "Red-Eyes B. Dragon": "Red_Eyes_Black_Dragon",
    "Dark Master Zorc": "Dark_Master_Zorc",
    "Queen's Double": "Queen_s_Double",
    "Y-Dragon Head": "Y_Dragon_Head",
    "Z-Metal Tank": "Z_Metal_Tank",
    "VW-Tiger Catapult": "VW_Tiger_Catapult",
    "Shinato King of a Higher Plane": "Shinato_King_of_a_Higher_Plane",
    "Nimble Momongas": "Nimble_Momonga",
    "Giant Germs": "Giant_Germ",
    "Skull Knight #2": "Skull_Knight_2",
    "Crystal": "Violet_Crystal",
    "Ojama": "Ojama_Token",
    # Equip spell names (quoted on Guardian monsters)
    "Wicked-Breaking Flamberge - Baou": "Wicked_Breaking_Flamberge_Baou",
    "Shooting Star Bow - Ceal": "Shooting_Star_Bow_Ceal",
    "Butterfly Dagger - Elma": "Butterfly_Dagger_Elma",
    "Gravity Axe - Grarl": "Gravity_Axe_Grar",
    "Rod of Silence - Kay'est": "Rod_of_Silence_Kay_est",
    "Twin Swords of Flashing Light - Tryce": "Twin_Swords_of_Flashing_Light_Tryce",
}

with open(JSON_PATH, encoding="utf-8") as f:
    data = json.load(f)

class_re = re.compile(r"^public sealed class (\w+)\s*:", re.M)
class_names: set[str] = set()
for dirpath, _, files in os.walk(CARDS_CS):
    for fn in files:
        if not fn.endswith(".cs"):
            continue
        with open(os.path.join(dirpath, fn), encoding="utf-8", errors="replace") as cf:
            for m in class_re.finditer(cf.read()):
                class_names.add(m.group(1))


def class_name_to_entry_id(cn: str) -> str:
    return "_".join(p.upper() for p in cn.split("_") if p)


eid_to_class: dict[str, str] = {}
for cn in class_names:
    eid_to_class[class_name_to_entry_id(cn)] = cn

# title -> eid: prefer longer / canonical keys (VW_TIGER over V_W) by sorting keys descending by length
title_to_eid: dict[str, str] = {}
keys_sorted = sorted(
    (k for k in data if k.startswith("YGODUELIST-") and k.endswith(".title")),
    key=len,
    reverse=True,
)
for k in keys_sorted:
    v = data[k]
    if not isinstance(v, str):
        continue
    eid = k.split(".")[0].replace("YGODUELIST-", "")
    if v not in title_to_eid:
        title_to_eid[v] = eid


def resolve_quote(q: str) -> str | None:
    if q in QUOTE_TO_CLASS:
        return QUOTE_TO_CLASS[q]
    eid = title_to_eid.get(q)
    if not eid:
        return None
    return eid_to_class.get(eid)


card_quotes: dict[str, set[str]] = defaultdict(set)
pat = re.compile(r'"([^"]+)"')
for k, v in data.items():
    if not k.startswith("YGODUELIST-") or not isinstance(v, str):
        continue
    parts = k.split(".", 1)
    if len(parts) < 2:
        continue
    card_id = parts[0].replace("YGODUELIST-", "")
    for m in pat.finditer(v):
        card_quotes[card_id].add(m.group(1))

# card_id (UPPER) -> host class name
host_re = re.compile(r"^public sealed class (\w+)\s*:", re.M)
ns_re = re.compile(r"^namespace\s+([\w.]+)\s*[;{]", re.M)
id_to_host: dict[str, str] = {}
class_to_namespace: dict[str, str] = {}
for dirpath, _, files in os.walk(CARDS_CS):
    for fn in files:
        if not fn.endswith(".cs"):
            continue
        path = os.path.join(dirpath, fn)
        with open(path, encoding="utf-8", errors="replace") as f:
            text = f.read()
        nsm = ns_re.search(text)
        ns = nsm.group(1) if nsm else ""
        m = host_re.search(text)
        if not m:
            continue
        cn = m.group(1)
        eid = class_name_to_entry_id(cn)
        id_to_host[eid] = cn
        if ns:
            class_to_namespace[cn] = ns


def fq(cn: str) -> str:
    n = class_to_namespace.get(cn)
    if not n:
        raise SystemExit(f"missing namespace for class {cn}")
    return f"global::{n}.{cn}"

lines: list[str] = [
    "// <auto-generated by tools/generate_preview_map_cs.py — do not hand-edit>",
    "using System;",
    "using System.Collections.Generic;",
    "using MegaCrit.Sts2.Core.HoverTips;",
    "using MegaCrit.Sts2.Core.Models;",
    "",
    "namespace YgoDuelist.YgoDuelistCode.Services",
    "{",
    "/// <summary>Maps card CLR types to quoted-card preview targets from localization.</summary>",
    "public static class YgoReferencedCardPreviewMap",
    "{",
    "    private static readonly Dictionary<Type, Type[]> Map = new()",
    "    {",
]

# Host cards that should not show any quoted-card previews (localization uses archetype text only).
NO_QUOTED_PREVIEWS_FOR_CARD_ID: frozenset[str] = frozenset({"ARSENAL_SUMMONER"})

EXODIA_CARD_ID = "EXODIA_THE_FORBIDDEN_ONE"
EXODIA_PREVIEW_ONLY_CLASS = "Left_Arm_of_the_Forbidden_One"

entries: list[tuple[str, list[str]]] = []
for cid in sorted(card_quotes.keys()):
    if cid in NO_QUOTED_PREVIEWS_FOR_CARD_ID:
        continue
    host = id_to_host.get(cid)
    if not host:
        continue
    resolved: list[str] = []
    seen: set[str] = set()
    for q in sorted(card_quotes[cid]):
        cn = resolve_quote(q)
        if cn is None:
            continue
        if cn not in class_names:
            continue
        if cn == host:
            continue
        if cn not in seen:
            seen.add(cn)
            resolved.append(cn)
    if cid == EXODIA_CARD_ID:
        resolved = [EXODIA_PREVIEW_ONLY_CLASS] if EXODIA_PREVIEW_ONLY_CLASS in class_names else []
    if resolved:
        entries.append((host, resolved))

for host, rlist in sorted(entries, key=lambda x: x[0]):
    inners = ", ".join(f"typeof({fq(c)})" for c in rlist)
    lines.append(f"        [typeof({fq(host)})] = new[] {{ {inners} }},")

lines.extend(
    [
        "    };",
        "",
        "    public static Type[] GetReferencedTypes(Type hostCardType)",
        "    {",
        "        if (!Map.TryGetValue(hostCardType, out Type[]? arr) || arr == null || arr.Length == 0)",
        "            return Array.Empty<Type>();",
        "        int keep = 0;",
        "        foreach (Type? t in arr)",
        "        {",
        "            if (t != null && t != hostCardType)",
        "                keep++;",
        "        }",
        "        if (keep == 0)",
        "            return Array.Empty<Type>();",
        "        if (keep == arr.Length)",
        "            return arr;",
        "        var filtered = new Type[keep];",
        "        int i = 0;",
        "        foreach (Type? t in arr)",
        "        {",
        "            if (t != null && t != hostCardType)",
        "                filtered[i++] = t;",
        "        }",
        "        return filtered;",
        "    }",
        "",
        "    public static IEnumerable<IHoverTip> EnumerateCardPreviewHoverTips(Type hostCardType)",
        "    {",
        "        foreach (Type t in GetReferencedTypes(hostCardType))",
        "        {",
        "            if (t == null)",
        "                continue;",
        "            CardModel template = YgoPackCardCatalog.CardFromType(t);",
        "            yield return HoverTipFactory.FromCard(template);",
        "        }",
        "    }",
        "}",
        "}",
        "",
    ]
)

os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
with open(OUT_PATH, "w", encoding="utf-8", newline="\r\n") as out:
    out.write("\r\n".join(lines))

print(f"Wrote {OUT_PATH} with {len(entries)} entries")
